# Generated by Django 2.0.3 on 2018-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180312_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('VIDEO & FLIM', 'VIDEO & FLIM'), ('MUSIC', 'MUSIC'), ('WRITING', 'WRITING'), ('COMICS & ILLUSTRATION', 'COMICS & ILLUSTRATION'), ('PODCASTS', 'PODCASTS'), ('GAMES', 'GAMES'), ('DRAWING & PAINTING', 'DRAWING & PAINTING'), ('ANIMATION', 'ANIMATION'), ('PHOTOGRAPHY', 'PHOTOGRAPHY'), ('SCIENCE', 'SCIENCE'), ('EDUCATION', 'EDUCATION'), ('CRAFT & DIY', 'CRAFT & DIY'), ('DANCE & THEATER', 'DANCE & THEATER'), ('EVERYTHING ELSE', 'EVERYTHING ELSE')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='donation',
            field=models.BigIntegerField(default=0),
        ),
    ]
